<?php
/**
 * Default structured content when DB sections are empty (first visit).
 * Used by public pages + admin editors for placeholder JSON.
 */
return [
    'about_timeline' => [
        ['year' => '2018', 'kind' => 'circle', 'title' => 'The Vision', 'body' => 'Conceptualization of a new standard in Abuja hospitality begins, focusing on blending local culture with global luxury.'],
        ['year' => '2020', 'kind' => 'dot', 'title' => 'Breaking Ground', 'body' => 'Construction commences in the diplomatic zone, utilizing sustainable materials and local artisans.'],
        ['year' => '2023', 'kind' => 'circle', 'title' => 'Soft Opening', 'body' => 'We opened our doors to select guests, refining our service to perfection before the grand unveiling.'],
        ['year' => '2024', 'kind' => 'dot_primary', 'title' => 'The Grand Reveal', 'body' => 'Lusso Hotels Abuja officially launches, setting a new benchmark for ultra-luxury experiences in the capital.'],
    ],
    'about_team' => [
        ['name' => 'Chike Okafor', 'role' => 'General Manager', 'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuC9eSNCQmjgxKcUyONGsNwOig_VRdoHvJI4L-p0W6lg8iGYTl76_k2lgoxIZhP5d2HDli4D115a-cp9Fhz00-iVVBKzZjm4QrUD0IRBMqNiU6r_fi8RmoTQnpKEJiNpCT7e1CUaxSQbiNP357UvkGWHJbg0KHE_twLJZ5Vw-RmqeoYsdhxAcuSjNb-hl0Rkm4KC3PrdPG6rw7CeU0xE29JZ6CJ8O4djJ1rREkqNWtRGtPYa1NX4YEx3SvsTOvpIp98LyinhSFtIwhs'],
        ['name' => 'Amina Yusuf', 'role' => 'Head of Guest Experience', 'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_5xoFkSSsrsPIRDbbzIMr3UDWb9D4F7y7WGeanAhOszymySAiLiWLHuc6jogUrOI_HPGGwRoRuirqBt1qYHbtvIwgW39ks7HHUp164pd62ltJ18su45G-CSiD27VLJpJnEDdqB5vwr7X_N4eiF1bQYIeLSrU0F0hsBN0Wri5KYDd8A1JaGCKRdDf2V0IBrEw5kiEPSUfiBCATLw-w4IB56LWUn-mse6hNj5FkZ7CsdLP3onei4CjfECHlHWWA-iKZm4Ybt1fhiZg'],
        ['name' => 'Chef Marco Rossi', 'role' => 'Executive Chef', 'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuD135utqrjUbJ0rgBRZxJxt2okEPhmfbuc8udn4VqKKCElXRbg6GEcnD_WppUbafALnhBSFrrBG_xj4ufwNH3AF2zFb4Vr39-aWeoENffkl_ujwcTNaB0R1F28HcbAc6KjAogFq4_2c3kszQOnirJdf_YBGx6c5sfNdiGbHUUo0NaSQLJVKOV1hulJKVq62GTjPi2wczeH2fm7k93TayhARL1ycmLGppgqdOiZIMrSQtGPY2SJtMNIqouVi45iyAVy8oC0cLMyc3aw'],
    ],
    'gallery_items' => [
        'https://lh3.googleusercontent.com/aida-public/AB6AXuA5tK8H1tXFtoYmo0oL5tKsXnBCgWKSeURy0RumMWpsSKm32ckRTi7VFSUP3-W5QF7QxpWJ0E6WGH4hIwg2i8Z5O25oyHH47bN1lU-8NuBWxg6SwxPBp-eHEAH6S9Glz1PT1YEP0OqnbxHmuLu8A1l6Me1aQDKg5EcItCrtWn29TWLCTTtYH6ZGaruO7zwTaCaYLTRSoS83In0tJPHA3w_StwQvbrMoVPaFlBCyYhodAndloPSeqF3ed1aeAcHSXCwpWmuDLdQkuOM',
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCIL8-UlI9lluP6OPokZYyTgaeCyz6V01zQBzd2SJe77iAWiZgGCjFiASJZTJ_nNvjwrteJEV-ZcHqPBbQkxsr9202ZoLgfdqa8OsknhIgBtr_ddrud-3JSkHclukrv8TLl1oz4srSBlBhzZvJrDyr79NYnt5tKe_GUwoyKFa8CgnaPaQvGKCOqdM1Dd8lCoyMWsVMf4VFbRHJ5p4wLUp4FAJdV3dqTkYFRB2oqjNZdR79a1ESIPSG1f4ZWFcJfssDvAnqMMoVtNYA',
        'https://lh3.googleusercontent.com/aida-public/AB6AXuD_25dPwoFo16k_Vy-edpEJNruHcWcr6RE-tAz1tAQrJaGEtaBsznnlVYOSegvzNgTJumDmddzKz9Kxy_FpGTfHfXH-q0ZIGFCzpCm8FQ5MImrToTrL-OJ8skdszcbM7zBk98wVGiUZ3lPRksZ6gltkYBWflB8G0p3gcB6fDj7F8g1CdVKA7zuECGjTl6XMWEWMSB7JOCEkApjPbtVc6D_iOpiwl65wXcRUlsixYDm9qwHXjzfwSarOyyg6EN0qFGvgDO45elmXmR4',
        'https://lh3.googleusercontent.com/aida-public/AB6AXuDgpjundkaiszzX591fYzdsY57Ve_XkuoOq3UYfy8sYKDOTJCvugNzwkp4XvpMI7ghgTs10eEf1icPH653-SZBfIXe12M9r4c84RqiMXsTQfHWAybvaY_qtLdUduPbeMzOq3o5rrYnxO8laGQLr6hHgURX_-1YHX-eSNhs5mn_6C7ruvw3yb2ogzJAZ42vIuqTByw2T8rJVJy_VoIfBdN_iEsfH7UotxiCAJshTvuUD30FNNaQ1uoetYTKw-USlZTojfBOh3MDf76o',
        'https://lh3.googleusercontent.com/aida-public/AB6AXuAKzWPolnBFpni4LOc-NKHKrUAmS7HvDWoi_AP-pFrcqm0yxmyOgFqoLhAlGkE5HAmnNaritkp6Ov9BI4YDpw95gjqMF_ldnVOnWkWcTEaBIbraGe0KgZfKUHr1CZzv2PDiWfeP6xxgQUFwlTgQ34RS-5guWQRenJKW0EIMq8l_ElmpH3iC-fPdRMDAuwecvot__luwspZORsUEOJNFBB-90f7NKpkBacl1lHaDeUx5WqnXm3RFI74fIKkQTdl3tzvu4trH2JOkyx0',
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBm3BlWwe0QOPeoBHZBaHuroLWT68bjQ7BYT40PbFr1hpa5syq_nX7VleEiD8Sw-ZwMRV_Tcn6rj1OT5fWS8Zh-CTUPKWrAVI1sywnUOUl8sbZJTFwXSM95f0DFM-88c1wJg0ZSDDkuA-4jgM3iikJeg8qborBmxjM0cdb0T5xNdTYBDaqwkmsfSNbvBwsEtgqPq3Pk_bPIsE9TZHfsoAfM0u8DqtZ6LQOkYooatRrU-RL3ThAzgmeoysNQ70rOgQpfgTFg4scrwMk',
        'https://lh3.googleusercontent.com/aida-public/AB6AXuAML1umnC6QckRZDDMIk6zoxjedPfdsHmB52eRdt3UHNIOUfllOGfwaERhFlUsmEB6izlNaFg2hM2nVvW95yo6knq7mduJas1gZZhhw59SAJBwBrM5zyKui9INzaB_jRbhmNnQ4sAdm2OVzWtsvF0IuCRdWHAyJRiMPo97P-3QJL_JqH1JqDI5nuptvk9RRv8azj9sghYKyyWUiF5UWVXEcF8crY34u5DdUHW7Zp-OZRAiRdWlejsZykyFdeyh2M11hiDTVYKKLh2E',
        'https://lh3.googleusercontent.com/aida-public/AB6AXuAFdoG8bL23KzVOUK94vr_9pM54wjg9a5MDfgsYPYmQ9UFdSJ3gFz7029d0av5AN54y7DfBH-JOFjUVMp0L2ORX2BSrc7iWf2HCx6h_52i4HBCq2o3N-OdYDo4J7l30wGSh7EEIj87g0cHCgnLVWOxF5F4W_kJqDzElwOuSzg0cBaMxVV3ZOd1DAFLG_hKtxx4e0rBoQQx7rEh5ywMMoK0S6b-SXiXJA1AgKRy7elj6zOoBeV0PSGtPic10VHRDxGrhrToBZYlZPRw'
    ],
    'dining_menu' => [
        ['name' => 'Truffle Tagliolini', 'desc' => 'Handmade pasta, aged parmesan foam, shaved black truffle from Norcia.', 'price' => '$45'],
        ['name' => 'Wild Caught Sea Bass', 'desc' => 'Pan-seared fillet, saffron risotto, caramelized fennel, citrus emulsion.', 'price' => '$62'],
        ['name' => 'Smoked Duck Breast', 'desc' => 'Cherry wood smoked, parsnip puree, blackberry reduction, crispy kale.', 'price' => '$58'],
        ['name' => 'Deconstructed Tiramisu', 'desc' => 'Espresso soaked sponge, mascarpone cloud, cacao nibs, marsala gel.', 'price' => '$24'],
    ],
    'dining_masonry' => [
        ['src' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrxdk_k0RbqP9VB9ZnTEMUCj_CizEyqF4so9f0wIUuljW-3LUPYI2viafk1f9KXdg-8gCm1bWnCyaF9Qii_FCjfRzMY8sdnPc3xPqTIXcRsNtyA7GaOLP4ugHhbGUM_80DpJ-c8sj9EsIyNTXKRNNlWwk9mZN5vPCMjFENcFKX6Wdi2RFMqhpGY2gr4Pze8Ar-0Gi3uqsHfw7BlFY2o5Ngwbl4EHWx0QO7AVgKeiIZGLyHrh0FhOFwJJJu8YcGcqEmUsd4FmFdcuo', 'tag' => 'Ambience', 'caption' => 'The Golden Hour at the Bar'],
        ['src' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuA4wPkY9N0PvhkmiOzPxfEALtoXB1LenOBsIY7AOmRVLaaPk_h59ar2_vMQbZWwWSaUTecCDmE5EVXck9ShgIG7GtRZ7gZbrh89ppQ-e5IMNyVXqgGQ16fdLLm1JTgs0eMZIInU_z0dKBk1j8uKJgPi3tfd5dp8b6SUWvDk29GQ7wwVcIVhP4t7LTEnn3Vqz27sFMkz_CEeWBGomnKnkCUPVWiTcXNdluH7JsCIK3BnHuyJh2BXKSbL9_q96VOeJDGIBxIwg8z6H2k', 'tag' => 'Signature', 'caption' => 'Wagyu A5 Selection'],
        ['src' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCCjqRu0IsMNgaPi023zgaiA4v4Ams6stVuXvd7mXiDJltyigOtEhnIAPYnDuN52lBVVR0RW4l9FPTHGuZalBQhHvJvwhd5HXoeFjuLuUQbPXOW5SNRuuqY4YVwrqZPv_oRXJIAZKLpEbL_XaUuED5Wzpg0Y4HfiD2l6QWMl5i_Xn11K-9cm89qcE4wI9mCF2bLspE0Io2RTN_zkbW5T4PTFhsADsRPZY0YjJhQGY8OYXMDtb1XgcIrmUOld7fOm4eukKjAcFHAHxU', 'tag' => '', 'caption' => ''],
        ['src' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCOzhV308G6AILXfGWhi_HSTDOC49ofNxNRUdf6w1xwdIJ3CqK4c7OqPkVqcMtQCLNdSb_oZ6b7ynQ1ZwwW6G0xYrwQKAeifKKCAd79_Z-ayfDXJaf7OZ6dKZHv4tbgJeVdrI-Vb_BxPxUnWCOdMWPMolLDcXZo2CQ02weUSJs5y9elECTIiOq4A8ZssNYAJsnT55UnhvlYuXNd2dHZjtU6TUcQFO1catARBdmBBusiYtyVJEgAGw_EadVAmJ18JUEMzNMOJw3-YSc', 'tag' => '', 'caption' => ''],
        ['src' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuB5jVi3S0RooEflMVhnkXSbi5AtR54xHxEn-boFaYXQSv3j-mXm68D4iLPU_zQwcjw-CzRJsTUJem0c2CGgc04_eigiHR6rZp0vcpw8AS7r6PQPfvhAy7cUyDjMTP7cLPik-p-J9rVhJBhRue6HAUnVNjiRbFHoT_D7Wru_DmPEPAYbtbMGY1hrzySB4zJ6d5LCNRCbMIsdcpgIJYHddizIMZ8l57If5qW8tCBcBmyeDH3jjsay8jXGLFnGWSHwlFpKgpi4rdh9CDA', 'tag' => '', 'caption' => ''],
    ],
    'amenities_sections' => [
        ['bg' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuATMWQ9ddjjOA4wFv31SyKAcfV08d7fzWQwJJLFw8W4nyvLVqP-p_-P0uKukQ-ymqZZsIuP1ACuW5Ffn40KZEAPKAcyIDOa3iDluP3hX3REtSLG-MAiNsjVpRAz2FswpZE5x84XZOcuKC0FB7-GxSEfuBR0RPuBNtVPJBRqgujF46zq2kUd-BbkyBcZyeXJmuBJL75gxLUJ80nf5zIXHHoyyRcyAdVagPBMBpxjRcaPB4dVF2_T-pznfhKnHQ-0aZoLiltivLISH_8', 'gradient' => 'linear-gradient(rgba(15, 15, 10, 0.3) 0%, rgba(15, 15, 10, 0.8) 100%)', 'kicker' => '01 / Dining', 'icon' => 'restaurant', 'title_html' => "The <br/> <span class=\"font-bold text-outline\">Palate</span>", 'body' => 'Culinary Theater. Experience gastronomic artistry in a dimly lit, intimate setting where every bite tells a story.', 'btn' => 'Reserve a Table', 'btn_href' => '/dining', 'layout' => 'bottom'],
        ['bg' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCLarwysjEyFZSto0gzEO4FKbW-tT8HC_JtNDfeLK7XsmKzytwSR_mkxuEztTjy5qTmsiwygCChQOycr9W0LBi3emO5uV27DHZvgpOy4XdjBHCkEcfV17PVVx7ZG_LTDu9wnMj2cu2EVqq2eUenXIgoiH25xJQngMP22xQ-wWU0Dxf1UbgzmAeE4qdm5ch3yUNQxbgPpbo_SSfbNnuQaXrrBuogiq97DEnbeGvJFnvJE_LXkXWrCv_bqC4F-3EkVSvLvtpQ6MGzlIw', 'gradient' => 'linear-gradient(rgba(20, 15, 5, 0.5) 0%, rgba(0, 0, 0, 0.6) 100%)', 'kicker' => '02 / Bar & Lounge', 'icon' => 'local_bar', 'title_html' => "The <br/> <span class=\"font-bold text-outline\">Alchemist</span>", 'body' => 'Rare Spirits & Mixology. A collection of the world\'s finest libations curated for the discerning palate.', 'btn' => 'View Menu', 'btn_href' => '/dining', 'layout' => 'right'],
        ['bg' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJDeHlcRp5ggr-cHXVvpFZ-qTOAxDmRpWhSow5j9iOdR5miM7-XlrIH3rtlXDK484Snj2m8evlCUFPZgFOM27czJuaKje8Q4j4kKZPIvRWEOAnF0X5ZVAUDMAPoREPOKVrAZ4fQsD92zJkTwBBP3h6zBkoYAa2LwX7qiD9CSbWlujhGVPsX4twNtGmuNj0AswfQmjB23pwJs1mbjm70xEjMvy3Vu0qatH4OG_HFlu5e9zIFuCXsVYoU8pnYfGipI2FpVpxbWdwhX0', 'gradient' => 'linear-gradient(to right, rgba(0, 0, 0, 0.7) 0%, rgba(0, 0, 0, 0.2) 100%)', 'kicker' => '03 / Infinity Pool', 'icon' => 'pool', 'title_html' => "The <br/> <span class=\"font-bold text-outline\">Sanctuary</span>", 'body' => 'Suspended Serenity. An infinity pool merging with the Abuja skyline at dusk, offering an oasis above the city.', 'btn' => 'Explore', 'btn_href' => '/amenities', 'layout' => 'top'],
        ['bg' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuA17HhM-Xy_vBjwPjiRaEkaaweheH07ry3g_oYfxznV8GnPs2j1DMaBZgN49FjgtbzMLLf7KXGdw-Ma2Qyozcb2nkAI3f_YcJiVnMrQZZMrep8JkOL0x-zlwGkvSD6UeJzQnhju0R7las0v_ovzUdAPIlhaMg1kxxVpFG4VwnkXxG-rzs9Rvob2MZEPpSEelJSjJDEz2P6GXWLkst79mL8c34PW1sGshqZ_vWb0Dp5gAkiQU4A_D3_AoUzPtdvi_cd3m7kAJJW_Ilc', 'gradient' => 'linear-gradient(to top, rgba(10, 10, 10, 0.9) 0%, rgba(10, 10, 10, 0.2) 100%)', 'kicker' => '04 / Wellness', 'icon' => 'fitness_center', 'title_html' => 'The <span class="font-bold text-outline">Foundry</span>', 'body' => 'Peak Performance. High-contrast wellness and state-of-the-art equipment designed for the dedicated.', 'btn' => 'Wellness Details', 'btn_href' => '/amenities', 'layout' => 'center'],
    ],
];
